server:
  port: 8084

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
