spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notification_db
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:password}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
