server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: admin
    password: password
  rabbitmq:
    host: rabbitmq

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
